# Generated by Django 4.0.4 on 2022-06-03 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('villageapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='titel',
            new_name='title',
        ),
    ]
