# Generated by Django 4.0.5 on 2022-06-05 10:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('villageapp', '0004_complaints_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('descritrion', models.TextField()),
                ('salary_desc', models.TextField()),
                ('no_of_opening', models.IntegerField()),
                ('contact_details', models.TextField()),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('location', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
