# Generated by Django 4.0.5 on 2022-06-05 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('villageapp', '0005_jobs'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
