# Generated by Django 4.0.5 on 2022-06-06 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('villageapp', '0007_alter_complaints_image_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='image',
            field=models.ImageField(upload_to='review_pics'),
        ),
    ]
