# Generated by Django 4.0.5 on 2022-06-08 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('villageapp', '0008_alter_review_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Userquery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('subject', models.TextField()),
            ],
        ),
    ]
