# Generated by Django 4.0.5 on 2022-06-08 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('villageapp', '0009_userquery'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userquery',
            old_name='Name',
            new_name='name',
        ),
    ]
